name: Monitor Metrô SP

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_metro:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install selenium pandas webdriver-manager requests

      - name: Executar Scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Commitar mudanças (se houver atualização)
        run: |
          git config --global user.name 'MetroBot'
          git config --global user.email 'bot@metro.sp'
          
          # Tenta adicionar os arquivos (o script garante que o JSON existe, mesmo vazio)
          git add estado_metro.json || echo "JSON não encontrado"
          git add historico_ocorrencias.csv || echo "CSV não encontrado"
          
          # Verifica se tem algo 'staged' (verde) para commitar
          if ! git diff --cached --quiet; then
            git commit -m "Atualizando status do metrô"
            git push
          else
            echo "Nenhuma mudança para salvar no repositório."
          fi
